import { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';

import Footer from '../../components/Footer';
import Header from '../../components/Header';

import Wrapper, { Title, EnsaioContent } from './style';

interface DataEnsaio {
    nomeCliente: string,
    url: string[],
    _id?: string,
}

interface EnsaioProps {
    dataEnsaio: DataEnsaio[]
}

export default function Ensaio ({ dataEnsaio }: EnsaioProps) {

    return (
        <>
            <Head>
                <title>Ensaio | {dataEnsaio[0].nomeCliente}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Header home={false} />

            {dataEnsaio != null && <Wrapper>
                    <Title>
                        <h1>Ensaio { dataEnsaio[0].nomeCliente }</h1>
                    </Title>
                    <EnsaioContent>
                        {dataEnsaio[0].url.map(urlImage => (
                            <img src={urlImage} key={urlImage}/>
                        ))}
                    </EnsaioContent>
                </Wrapper>
            }

            <Footer/>
        </>
    )
}

export const getStaticPaths: GetStaticPaths = async () => {
  
    return ({
        paths: [],
        fallback: 'blocking'
    })
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
    const { id } = params!;

    const data = await fetch(`${process.env.BACK_END_URL}/getImages`);
    let dataEnsaio: DataEnsaio[] = await data.json();

    dataEnsaio = dataEnsaio.filter((ensaio) => {
        return id == ensaio._id
    })

    return ({
        props: {
            dataEnsaio
        }
    })
}