import Head from "next/head";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import Button from "../../components/utility/Button";

import Wrapper from "./style";

export default function Fotografa() {
    
    return (
        <>
            <Head>
                <title>A Fotógrafa | Ângela Reys Fotografia</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Header home={false} />

            <Wrapper>
                <div>
                    <h1>
                        Hello Pessoinhas
                    </h1>
                    <p>
                        Me chamo Ângela Reys, sou do interior da Bahia de uma cidadezinha chamada São Felipe. Sou fotógrafa especializada em retratar a beleza feminina há alguns anos. Meu maior propósito é fazer com que você se lembre a mulher linda, maravilhosa e poderosa que você é!<br /><br />

                        Eu quero te ajudar a enxergar álem dessa visão distorcida que você tem de se mesma, e te mostrar através das minhas lentes, as suas qualidades, suas boas caracteriticas e até mesmo a aceitar as que não te agradam muito.<br /><br />

                        Meus ensaios acontecem de maneira leve e divertida. Não se preocupe se você não for modelo, até porque você não precisa ser para fazer um ensaio. Eu vou tá lá pra te ajudar a se posicionar, te dar dicas como fazer poses. Eu te garanto que vai ser uma experiência divertida!<br /><br />

                        Uma mulher com a autoestima elevada te dará o poder para alcançar seus sonhos e maiores desejos. Através do meu trabalho vou mostrar o quão maravilhosa você é!<br /><br />
                    </p>
                    <Button caminho="/contato">Solicite um orçamento</Button>
                </div>
                <div>
                    <img src="/Angela01.jpg" alt="Ângela Reys - Fotógrafa" />
                </div>
            </Wrapper>
            
            <Footer/>
        </>
    )
}