import type { NextPage } from 'next';
import { GetStaticProps } from 'next';
import Head from 'next/head';

import Header from '../components/Header';
import Carrocel from '../components/Carrocel';
import Footer from '../components/Footer';
import VideoConteiner from '../components/VideoConteiner';
import Depoimentos from '../components/Depoimentos';
import RecentWorks from '../components/TrabalhosRescentes';

interface RecentWorks {
  _id: string,
  key: string,
  capa: string,
  nomeCliente: string,
  tipoEnsaio: string,
}

interface HomeProps {
  ensaiosRecentes?: RecentWorks[]
}

const Home: NextPage = ({ ensaiosRecentes }: HomeProps) => {

  console

  return (
    <>
      <Head>
        <title>Home | Ângela Reys Fotografia</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header home={true} />

      <main>
        <Carrocel />
        <VideoConteiner />
        <RecentWorks ensaiosRecentes={ensaiosRecentes} />
        <Depoimentos />
      </main>

      <Footer />
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
    
  let ensaiosRecentes: RecentWorks[] = [];
  
  let data = await fetch("https://app-api-photos.herokuapp.com/getImages");
  let datajson = await data.json();
  for(let i = datajson.length - 1; i > datajson.length - 7; i--){
      if(datajson[i] != undefined){
          ensaiosRecentes.push(datajson[i])
      }
  }

  return ({
    props: {
      ensaiosRecentes
    },
    revalidate: 60 * 60 * 24 // 24 hrs
  })
};

export default Home
